spring.application.name=MediBook
server.port=8080

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gurunathmule825@gmail.com
spring.mail.password=oioh frnw gtlv kkoc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cors.allowed.origins=http://localhost:5173

jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation2026!
jwt.expiration.ms=jwt.expiration=86400000

razorpay.key.id=rzp_test_SlFYFXNo3rq3G6
razorpay.key.secret=5stxGtEmUaz6NLdahCOWmBEt
frontend.url=http://localhost:5173

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=./uploads

app.name=MediBook
app.email.from=noreply@medibook.com
